server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_user?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver